spring:
  datasource:
    url: jdbc:mysql://root:RYDqRSpBAzfYFDHhwCQJaGmsEsSJiAwY@monorail.proxy.rlwy.net:56915/railway
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: RYDqRSpBAzfYFDHhwCQJaGmsEsSJiAwY